---
- name: Initial Configuration
  hosts: production
  remote_user: root
  vars_files:
    - ./default/vars.yml
    - ./group_vars/n8n/vars.yml

  handlers:
    - include: ./handlers/main.yml

  tasks:
    - include: ./tasks/users.yml
    - include: ./tasks/server.yml
    - include: ./tasks/security.yml
    - include: ./tasks/swapfile.yml
    - include: ./tasks/certificate.yml
    - include: ./tasks/server-post-certificate.yml

- name: Start App
  hosts: production
  remote_user: "{{system_user}}"
  vars_files:
    - ./default/vars.yml
    - ./group_vars/n8n/vars.yml

  roles:
    - role: ansible-role-nvm
      nodejs_version: "18.17.0"
      
  post_tasks:
    - include: ./tasks/project.yml