
- name: get node version
  slurp:
    src: "/home/{{ssh_user}}/.nvm/alias/default"
  register: nodeVersion
  
- name: "Make npm_path string"
  set_fact:
    npm_path: "/home/{{ssh_user}}/.nvm/versions/node/v{{ nodeVersion['content'] |b64decode | trim }}/bin/"

- name: Install N8N
  npm:
    name: n8n
    global: yes
    state: present
  environment:
    PATH: "{{ ansible_env.PATH }}:{{npm_path}}"

- name: Install pm2
  npm:
    name: pm2
    global: yes
    state: present
  environment:
    PATH: "{{ ansible_env.PATH }}:{{npm_path}}"

- name: Template PM2 Ecosystem
  template:
    src: ../templates/noodemation.j2
    dest: ~/ecosystem.config.js  

- name: Start or Reload App
  shell: pm2 startOrReload ecosystem.config.js
  args:
    chdir: ~/
  environment:
    PATH: "{{ ansible_env.PATH }}:{{npm_path}}"

- name: Add PM2 to startup
  become: true
  command: "pm2 startup systemd -u {{ssh_user}} --hp /home/{{ssh_user}}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{npm_path}}"

- name: Save PM2 Processes
  command: "pm2 save"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{npm_path}}"